steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/notion-budget-planner/notion-budget-planner', '.']
    env:
      - 'DOCKER_BUILDKIT=1'

images:
  - 'gcr.io/notion-budget-planner/notion-budget-planner'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  requestedVerifyOption: VERIFIED

serviceAccount: 'projects/notion-budget-planner/serviceAccounts/1005781479849-compute@developer.gserviceaccount.com' 