steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/notion-budget-planner', '.']
  env:
    - 'DOCKER_BUILDKIT=1'

# Deploy container image to the 'notion' service in Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'notion' # <-- Deploy to the 'notion' service
  - '--image=gcr.io/$PROJECT_ID/notion-budget-planner'
  - '--region=us-east1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--service-account=1005781479849-compute@developer.gserviceaccount.com'
  - '--set-env-vars=NODE_ENV=production'
  - '--set-secrets=NOTION_TOKEN=NOTION_TOKEN:latest,DATABASE_ID=DATABASE_ID:latest'

# Push the container image to Container Registry
images:
- 'gcr.io/$PROJECT_ID/notion-budget-planner'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  requestedVerifyOption: VERIFIED

serviceAccount: 'projects/notion-budget-planner/serviceAccounts/1005781479849-compute@developer.gserviceaccount.com' 